apiVersion: apps/v1
kind: Deployment 
metadata:
  name: petclinic-deployment
spec:
  selector:
    matchLabels:
      app: petclinic
  replicas: 2
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: youssef035/petclinic:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 


---

apiVersion: v1
kind: Service
metadata: 
  name: petclinic-svc
spec:
  selector:
    app: petclinic
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080 
  type: LoadBalancer 
